### ISSUE TITLE
tray issues

### ISSUE THREAD

**Issue by osa1** [sLite/i3#1]
I was wondering if it's possible to use i3's tray for all the KDE things, like sound, network, keyboard etc. widgets. Is there a way to do that?

Thanks.

**Comment by sLite** [comment]
AFAIR the i3 bar has a systemtray built in and the KDE apps put their icon there if you start them without a running KDE session. So you could just autostart the KDE apps you need from your i3 config and they should use the i3 bar for their icons, if that's what you want.
Or you could try to remove all kde panels or the systemtray from the kde panel and try to restart your session.

But i have no personal experience on that topic because my goal with KDE + i3 was exactly the opposite. ;)

**Comment by osa1** [comment]
Thanks for the answer. Actually I don't feel strong about either of the bars, so using only KDE panel also works for me, but for some reason I can't create a KDE panel that sits in the bottom all the time. Any ideas how to do it?

To be more specific, I can create a new KDE panel which sits on top of the screen, but I can't move it to bottom, for some reason it just doesn't pin to bottom part of the screen.

Btw, thanks for your effort, this finally bring me a good desktop experience. (i3 for WM, KDE for services)

**Comment by sLite** [comment]
hmm yea, it's the same here. i never tried that so far because the i3 bar sits at the bottom of the screen and i didn't want them in the same place.
I have no idea what the reason for this is, and i doubt i will be able to track it down.

I have zero to no experience with X11 lowlevel stuff and window management. I was able to adapt and trial&error my way around the patches that i have applied so far. But that behaviour is a different beast to deal with.

This would need someone with more profound knowledge of X11 and i3 itself to track this down.
You could try with the upstream i3 developers, but i doubt they are willing to track down bugs related to KDE as they don't really support KDE in the first place.

Sorry to let you down on this one, but i'm not experienced enough to fix this.

i3 bar bottom + kde panel top work together without issues, i would recommend that setup.

**Comment by sLite** [comment]
hmm, i just experimented a bit more. 

sometimes when you add a new panel, it pins itself to the bottom of the screen right when creating it.
so it seems to be possible to have panels at the bottom of the screen, just moving an existing one there seems to be broken...
