### ISSUE TITLE
Click Empty desktop doesn't focus that workspace

### ISSUE THREAD

**Issue by eva7sk** [sLite/i3#2]
Sorry for my english
For example, startup i3, and open an application in monitor 1 and move it to monitor 2
now, workspace 1 is empty, and click the desktop of workspace 1 it doesn't focus workspace 1(i3status not highlighted)
and then click kde logo in the bottem left, this will popup in monitor 2(wrong place)

**Comment by sLite** [comment]
yea, that is a known issue for windows that can't receive focus like panels and desktop.

i might look into that when i try the new i3 version, but i guess the hacks needed for this to work properly are just too ugly to be worth it.
if you can come up with a solution please tell me :)

**Comment by eva7sk** [comment]
@sLite Sorry for my late reply, I just realized it's the problem of i3, i was put wrong place
Could you close this issue?

**Comment by wzuo** [comment]
@sLite any reflection how to do this? this is important issue for me, and I want to have it fixed. where can I look in code in order to fix it?

**Comment by sLite** [comment]
I have removed special handling for the desktop window as a whole, because a desktop isn't really usefull for a tiling window manager anyway...

The desktop now pops up as a floating window if you don't make any special configuration.

```for_window [title="Desktop — Plasma"] kill;```

In your i3 config will get rid of them and leave you with a black background that is clickable like it should.

**Comment by sLite** [comment]
I updated the repo to upstream i3 and put up recommeded configuration options in the README.md.

I removed special handling for the desktop windows because i never use them and kill them via a config option now. The desktop is never visible anyway when running a tiling windowmanager, also the unmanaged desktop window prevented focusing a different monitor by clicking on the background.

While doing all that, i noticed that vanilla i3 doesn't seem to have any problems with Plasma anymore. So this repo might get archived at some point.

Please refer to the README to see all necessary options.

On this topic, did/do you use the plasma desktop?
